(setq bd ())
(setq bd (matricular '(augusto bruno) '(paradigmas calculo) bd))
(setq bd (vincular '(dani otavio) '(paradigmas calculo) bd))
(alunos? bd)
(disciplinas? bd)
(professores? bd)
(cursa? 'augusto bd)
(ministra? 'dani bd)
(setq bd (cancelar-matricula '(augusto) '(calculo) bd))
(setq bd (remover-vinculo '(dani otavio) '(paradigmas calculo) bd))